### ISSUE TITLE
大佬，有个视频下载不了，方便的时候看一下，辛苦了。

### ISSUE THREAD

**Issue by LvDeShei** [LuckyLi706/short_video_spider_client#11]
地址：
4.10 nQx:/ # 名人名言 # 每日书摘 # 人生哲理 # 智慧 https://v.douyin.com/reY2Nas/ 复制此链接，打开Dou音搜索，直接观看视频！
![image](https://user-images.githubusercontent.com/49177549/200460326-ba547130-9c70-4294-96eb-5241af80af4c.png)

**Comment by LuckyLi706** [comment]
应该是之前服务器挂了，现在应该可以，服务已经更新了
