### ISSUE TITLE
{code: 500, des: 系统内部出现异常，[Errno Expecting value] : 0}

### ISSUE THREAD

**Issue by cydevdummy001** [LuckyLi706/short_video_spider_client#12]
老哥是我配置不对吗？试了长链接和短链接，都是一样的错误。

```>>>>>>>获取视频地址失败：{code: 500, des: 系统内部出现异常，[Errno Expecting value] : 0}```

https://www.douyin.com/user/MS4wLjABAAAA_py8TGmFe6t8KDY04LU0JH9Yr9ml54dCjRFi0mc1lwI?vid=7056005623917448462
https://v.douyin.com/kN5rhLQ/

![01](https://user-images.githubusercontent.com/118442623/210428963-9a1c01a2-4a2c-41f4-9ae7-320e7db1996f.png)
![02](https://user-images.githubusercontent.com/118442623/210428969-624ed55c-45df-4fe3-bf07-4367e8f65fc1.png)

**Comment by cydevdummy001** [comment]
http://81.68.122.109:8080/douyin/single?url=https://v.douyin.com/2jA2dGq/&is_origin=0

啊，原来是服务端的问题
```系统内部出现异常```

**Comment by LuckyLi706** [comment]
嗯，现在需要Cookie了，我服务器也到期了，可以自己去搭建本地服务器。服务器代码改过了。
