### ISSUE TITLE
文件名能否支持自定义，下载报错，名字太长了

### ISSUE THREAD

**Issue by hsf25737** [LuckyLi706/short_video_spider_client#3]

**Comment by LuckyLi706** [comment]
给链接，我看看。

**Comment by hsf25737** [comment]
1.76 srE:/ “我携满天星辰以赠你，仍觉满天星辰不及你.ᴵ ᵇʳᵒᵘᵍʰᵗ ᵃˡˡ ᵗʰᵉ ˢᵗᵃʳˢ ᵃˢ ᵃ ᵍⁱᶠᵗ ᵗᵒ ʸᵒᵘ, ᵇᵘᵗ ᴵ ˢᵗⁱˡˡ ᶠᵉᵉˡ ᵗʰᵃᵗ ᵃˡˡ ᵗʰᵉ ˢᵗᵃʳˢ ᵃʳᵉ ⁱⁿᶠᵉʳⁱᵒʳ ᵗᵒ ʸᵒᵘ.”%治愈系  https://v.douyin.com/Y5RwxTp/ 复制此链接，打开Dou音搜索，直接观看视频！

**Comment by LuckyLi706** [comment]
告知一下在哪个平台测试的，我这边在Windows平台测试的没有问题，可以的话可以录屏，或者截取具体错误信息。

**Comment by hsf25737** [comment]
Android平台 ![微信图片_20220803135221](https://user-images.githubusercontent.com/26355320/182534447-22ff16d3-4237-4294-b3d7-dc8ed63e8b39.jpg)

**Comment by LuckyLi706** [comment]
好的，问题已经修复，确实是安卓的问题，试试看安卓1.1.2版本。
