### ISSUE TITLE
windows客户端 系统内部出现异常

### ISSUE THREAD

**Issue by qq137580756** [LuckyLi706/short_video_spider_client#6]
获取视频地址失败：{code: 500, des: 系统内部出现异常，list index out of range}

**Comment by qq137580756** [comment]
douyin

**Comment by LuckyLi706** [comment]
> 获取视频地址失败：{code: 500, des: 系统内部出现异常，list index out of range}

你获取多个视频的时候上面的选择框切换到多个，或者给个链接我看看呢~

**Comment by qq137580756** [comment]
&nbsp;https://v.douyin.com/jqjjYrP/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckyLi706/short_video_spider_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 上午7:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LuckyLi706/short_video_spider_client] windows客户端 系统内部出现异常 (Issue #6)





  
获取视频地址失败：{code: 500, des: 系统内部出现异常，list index out of range}
  
你获取多个视频的时候上面的选择框切换到多个，或者给个链接我看看呢~

**Comment by LuckyLi706** [comment]
没问题呀，我试了一下，直接复制这个链接https://v.douyin.com/jqjjYrP/

**Comment by qq137580756** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckyLi706/short_video_spider_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 中午12:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LuckyLi706/short_video_spider_client] windows客户端 系统内部出现异常 (Issue #6)





 
没问题呀，我试了一下，直接复制这个链接https://v.douyin.com/jqjjYrP/
